import { base } from '@bwmp-dev/eslint-config/base'

export default [
  ...base,
  // Generated by `prepack`; the editable copies live in /templates.
  { ignores: ['templates/**'] },
  { files: ['**/*.mjs'], rules: { 'no-console': 'off' } },
]
